name: Build DatabaseBuilder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish executable
      run: |
        dotnet publish DatabaseBuilder.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: DatabaseBuilder
        path: |
          bin/Release/net8.0-windows/win-x64/publish/DatabaseBuilder.exe
